/* 菜单配置js */

const MenuConfig = [
  {
    level: 0,
    name: 'System Management',
    index: 1,
    role: 'SM',
    path: 'home',
    icon: 'user',
    children: [
      {
        level: 1,
        name: 'People Management',
        path: '/uplending/peoplemanagement',
        index: 1,
        role: 'System User ',
      },
      {
        level: 1,
        name: 'Auth Role Management',
        path: '/uplending/authrolemanagement',
        index: 2,
        role: 'Role Management',
      },
      {
        level: 1,
        name: 'Resources Management',
        path: '/uplending/resourcemanagement',
        index: 3,
        role: 'Resources Management',
      },
      {
        level: 1,
        name: 'Password Modify',
        path: '/uplending/passwordmodify',
        index: 4,
        role: 'Password Modification',
      },

      {
        level: 1,
        name: 'Collection Management',
        path: '/uplending/creditdispatch',
        index: 20,
        role: 'CreditDispatch',
      },

      {
        level: 1,
        name: 'Evaluation Management',
        path: '/uplending/evaluationdispatch',
        index: 21,
        role: 'evaluationdispatch',
      },
      {
          level: 1,
          name: 'Call Retrieve Management',
          path: '/uplending/callretrievemanagement',
          index: 22,
          role: 'Call Retrieve Management',
      },
      {
          level: 1,
          name: 'Mail Center',
          path: '/uplending/mailCenter',
          index: 23,
          role: 'Mail Center',
      },

    ],
  },
  {
    level: 0,
    name: 'Operation Management',
    index: 2,
    role: 'OM',
    path: 'home',
    icon: 'bars',
    children: [
      {
        level: 1,
        name: 'Evaluation',
        path: '/uplending/loanaudit',
        index: 1,
        role: 'Evaluation',
      },
      {
        level: 1,
        name: 'Revaluation',
        path: '/uplending/revaluation',
        index: 8,
        role: 'Revaluation',
      },

      {
        level: 1,
        name: 'Post-Loan',
        path: '/uplending/postloan',
        index: 2,
        role: 'Post-loan',
      },
      {
        level: 1,
        name: 'Credit Collection',
        path: '/uplending/creditcollection',
        index: 7,
        role: 'Credit Collection',
      },
      // {
      // level: 1,
      // name: 'Credit Report',
      // path: '/uplending/creditreport',
      // index: 16,
      // role: 'CreditReport',
      // },
      {
        level: 1,
        name: 'User Information',
        path: '/uplending/userinformation',
        index: 10,
        role: 'User Information',
      },
      {
        level: 1,
        name: 'Input Order',
        path: '/uplending/inputorder',
        index: 9,
        role: 'InputOrder',
      },
      {
        level: 1,
        name: 'Consult Messages',
        path: '/uplending/feedback',
        index: 6,
        role: 'Consult Messages',
      },
      // {
      // level: 1,
      // name: "风控策略",
      // path: 'om-fc',
      // index: 3,
      // role: "风控策略",
      // },
      // {
      //   level: 1,
      //   name: "Operation Data",
      //   path: '/uplending/operationdata',
      //   index: 4,
      //   role: "Operation Data",
      // },
      // {
      // level: 1,
      // name: "会员",
      // path: 'om-hy',
      // index: 5,
      // role: "会员",
      // },
      {
        level: 1,
        name: 'Funds Management',
        path: '/uplending/fundmanagement',
        index: 3,
        role: 'Funds Management ',
      },
      {
        level: 1,
        name: 'Banner Management',
        path: '/uplending/bannermanagement',
        index: 11,
        role: 'bannermanagement',
      },
      // {
      //   level: 1,
      //   name: 'Collection Report',
      //   path: '/uplending/collectionreport',
      //   index: 12,
      //   role: 'Collection Report',
      // },
      // {
      // level: 1,
      // name: "Journal Account",
      // path: '/uplending/journalAccount',
      // index: 13,
      // role: "Journal Account",
      // },
      {
        level: 1,
        name: 'Payment Failed',
        path: '/uplending/paymentfailed',
        index: 14,
        role: 'Payment Failed',
      },

      // {
      // level: 1,
      // name: "Payment Failed",
      // path: '/uplending/paymentfailed',
      // index: 17,
      // role: "Payment Failed",
      // },

      {
        level: 1,
        name: 'Risk Management',
        path: '/uplending/riskmanagement',
        index: 18,
        role: 'Risk Management',
      },
      {
        level: 1,
        name: 'Operating Tool',
        path: '/uplending/operatingtool',
        index: 4,
        role: 'Role Operating Tool'
      },
      // {
      //   level: 1,
      //   name: 'Call Retrieve',
      //   path: '/uplending/callsale',
      //   index: 5,
      //   role: 'Role Call Sale',
      // },
      {
        level: 1,
        name: 'Call Retrieve(New)',
        path: '/uplending/callsaleNew',
        index: 99,
        role: 'Role Call Sale',
      },
      // {
      // level: 1,
      // name: "Risk Report",
      // path: '/uplending/riskreport',
      // index: 19,
      // role: "riskreport",
      // },
      // {
      // level: 1,
      // name: "Demo",
      // path: '/uplending/demo',
      // index: 16,
      // role: "Password Modification",
      // },
      // {
      //   level: 1,
      //   name: '',
      //   path: '/uplending/home',
      //   index: 15,
      //   role: 'Password Modification',
      // },
      {
        level: 1,
        name: 'Market Rules Engine',
        path: '/uplending/marketrulesengine',
        index: 13,
        role: 'marketing engine',
      },
      {
          level: 1,
          name: 'Coupon Management',
          path: '/uplending/couponManagement',
          index: 14,
          role: 'Coupon Management',
      },
      {
          level: 1,
          name: 'Activity Management',
          path: '/uplending/activityManagement',
          index: 15,
          role: 'Activity Management',
      },
      {
          level: 1,
          name: 'Promotion',
          path: '/uplending/promotion',
          index: 23,
          role: 'promotion',
      },
    ],
  },
  // {
  //   level: 0,
  //   name: 'Operating Tool',
  //   index: 5,
  //   role: 'OM',
  //   path: 'home',
  //   icon: 'bars',
  //   children: [
  //     {
  //       level: 1,
  //       name: 'Operating Tool',
  //       path: '/uplending/operatingtool',
  //       index: 1,
  //       role: 'Role Operating Tool',
  //     },
  //   ],
  // },
  {
    level: 0,
    name: 'BI System',
    index: 3,
    role: 'OM',
    path: 'home',
    icon: 'bars',
    children: [
      {
        level: 1,
        name: 'Collect Report',
        path: '/uplending/creditreportWithTab',
        index: 1,
        role: 'Collect Report',
      },
      {
        level: 1,
        name: 'Risk Report',
        path: '/uplending/riskreport',
        index: 2,
        role: 'Risk Report',
      },

      {
        level: 1,
        name: 'Operation Report',
        path: '/uplending/operatorReporterWithTab',
        index: 3,
        role: 'Operation Report',
      },

      {
        level: 1,
        name: 'Operation Data',
        path: '/uplending/operationdata',
        index: 4,
        role: 'Operation Data',
      },
      {
        level: 1,
        name: 'Traffic Monitor',
        path: '/uplending/adjustsearchtool',
        index: 5,
        role: 'Traffic Monitor',
      },
      {
        level: 1,
        name: 'APP Monitor',
        path: '/uplending/appMonitor',
        index: 6,
        role: 'APP Monitor',
      },
        {
            level: 1,
            name: '葵花宝典',
            path: '/uplending/bimainProcess',
            index: 7,
            role: 'Bi Main Process',
        },
    ],
  },
  {
    level: 0,
    name: 'Business Monitors',
    index: 4,
    role: 'OM',
    path: 'home',
    icon: 'bars',
    children: [
      {
        level: 1,
        name: 'Funds Monitors',
        path: '/uplending/moneymonitor',
        index: 1,
        role: 'Role Business Monitors',
      },
      {
        level: 1,
        name: 'Special Record',
        path: '/uplending/specialrecord',
        index: 2,
        role: 'Role Business Monitors',
      },
    ],
  },
  {
    level: 0,
    name: 'Loan Fair',
    index: 5,
    role: 'OM',
    path: 'home',
    icon: 'bars',
    children: [
      {
        level: 1,
        name: 'Company',
        path: '/uplending/cooperationCompany',
        index: 1,
        role: 'Role Loan Fair Page',
      },
      {
        level: 1,
        name: 'Product',
        path: '/uplending/cooperationProduct',
        index: 2,
        role: 'Role Loan Fair Page',
      },
    ],
  },
  {
    level: 0,
    name: 'Monitor',
    index: 6,
    role: 'OM',
    path: 'home',
    icon: 'bars',
    children: [
      {
          level: 1,
          name: 'Monitoring Data',
          path: '/uplending/monitorData',
          index: 1,
          role: 'Monitoring Data',
      },
        {
            level: 1,
            name: 'Main Process',
            path: '/uplending/mainProcess',
            index: 2,
            role: 'Monitoring Data',
        },
    ],
  },
  {
      level: 0,
      name: 'Data Monitor',
      index: 7,
      role: 'OM',
      path: 'home',
      icon: 'bars',
      children: [
          {
              level: 1,
              name: 'Data Source',
              path: '/uplending/datasource',
              index: 1,
              role: 'Data Monitor',
          },
          {
              level: 1,
              name: 'Rules',
              path: '/uplending/alertrules',
              index: 2,
              role: 'Data Monitor',
          },
          {
              level: 1,
              name: 'Abnormal Log',
              path: '/uplending/abnormallog',
              index: 3,
              role: 'Data Monitor',
          },
      ],
  },
  {
      level: 0,
      name: '规则引擎',
      index: 8,
      role: 'OM',
      path: 'home',
      icon: 'bars',
      children: [
          {
              level: 1,
              name: '首页',
              path: '/uplending/riskhome',
              index: 1,
              role: 'Risk Control',
          },
          {
              level: 1,
              name: '指标管理',
              path: '/uplending/indicatormanagement',
              index: 2,
              role: 'Risk Control',
          },
          {
              level: 1,
              name: '规则管理',
              path: '/uplending/rulemanagement',
              index: 3,
              role: 'Risk Control',
          },
          {
              level: 1,
              name: '规则组管理',
              path: '/uplending/rulegroupmanagement',
              index: 4,
              role: 'Risk Control',
          },
          {
              level: 1,
              name: '用户群管理',
              path: '/uplending/usergroupmanagement',
              index: 5,
              role: 'Risk Control',
          },
          {
              level: 1,
              name: '决策流管理',
              path: '/uplending/strategymanagement',
              index: 6,
              role: 'Risk Control',
          },
          {
              level: 1,
              name: '决策查询',
              path: '/uplending/strategyquery',
              index: 7,
              role: 'Risk Control',
          },
          {
              level: 1,
              name: '系统参数',
              path: '/uplending/systemparams',
              index: 8,
              role: 'Risk Control',
          },
      ],
  },
  {
    level: 0,
    name: '监控系统',
    index: 9,
    role: 'OM',
    path: 'home',
    icon: 'bars',
    children: [
        {
            level: 1,
            name: '指标相关',
            path: '/uplending/indicatorsRelated',
            index: 1,
            role: '指标相关',
        },
        {
          level: 1,
          name: '规则相关',
          path: '/uplending/rulesRelated',
          index: 2,
          role: '规则相关',
      },
      {
        level: 1,
        name: '通知记录',
        path: '/uplending/notifyRecord',
        index: 3,
        role: '通知记录',
    },
    ],
},
];

export default MenuConfig;
